# Generated by Django 3.1 on 2020-09-03 17:45

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
        migrations.AlterField(
            model_name='job',
            name='puplished_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
