# Generated by Django 3.1 on 2020-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200903_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='puplished_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
